### ISSUE TITLE
Error when leaving server

### ISSUE THREAD

**Issue by morgan2233** [RobiFox/BlockQuest#13]
# Template
**Describe the issue**
Error being produced when a user leaves the server

**Reproduction**

1. Join Server
2. Leave Server

```
[15:35:58 ERROR]: Hub1 > Could not pass event PlayerQuitEvent to BlockQuest v2.2.3
[15:35:58 INFO]: Hub1 > java.lang.NullPointerException: null
[15:35:58 INFO]: Hub1 >         at me.robifoxx.blockquest.inherits.CacheStorage.save(CacheStorage.java:72) ~[?:?]
[15:35:58 INFO]: Hub1 >         at me.robifoxx.blockquest.listener.CacheListener.leave(CacheListener.java:29) ~[?:?]
[15:35:58 INFO]: Hub1 >         at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor320.execute(Unknown Source) ~[?:?]
[15:35:58 INFO]: Hub1 >         at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-496]
[15:35:58 INFO]: Hub1 >         at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-496]
[15:35:58 INFO]: Hub1 >         at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-496]
[15:35:58 INFO]: Hub1 >         at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-496]
[15:35:58 INFO]: Hub1 >         at net.minecraft.server.v1_16_R3.PlayerList.disconnect(PlayerList.java:516) ~[patched_1.16.5.jar:git-Paper-496]
[15:35:58 INFO]: Hub1 >         at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1695) ~[patched_1.16.5.jar:git-Paper-496]
[15:35:58 INFO]: Hub1 >         at com.denizenscript.denizen.nms.v1_16.impl.network.handlers.AbstractListenerPlayInImpl.a(AbstractListenerPlayInImpl.java:365) ~[?:?]
[15:35:58 INFO]: Hub1 >         at net.minecraft.server.v1_16_R3.NetworkManager.handleDisconnection(NetworkManager.java:502) ~[patched_1.16.5.jar:git-Paper-496]
[15:35:58 INFO]: Hub1 >         at net.minecraft.server.v1_16_R3.ServerConnection.c(ServerConnection.java:165) ~[patched_1.16.5.jar:git-Paper-496]
[15:35:58 INFO]: Hub1 >         at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1387) ~[patched_1.16.5.jar:git-Paper-496]
[15:35:58 INFO]: Hub1 >         at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.5.jar:git-Paper-496]
[15:35:58 INFO]: Hub1 >         at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1214) ~[patched_1.16.5.jar:git-Paper-496]
[15:35:58 INFO]: Hub1 >         at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1002) ~[patched_1.16.5.jar:git-Paper-496]
[15:35:58 INFO]: Hub1 >         at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175) ~[patched_1.16.5.jar:git-Paper-496]
[15:35:58 INFO]: Hub1 >         at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by RobiFox** [comment]
Should be fixed. Thank you for reporting.
