### ISSUE TITLE
Update to 1.14.4 possible?

### ISSUE THREAD

**Issue by quorn23** [RobiFox/BlockQuest#9]
Sadly the 1.13 update isn't working for 1.14.4 the "blocks" won't show up and the server log is getting spammed with errors like this (i have an egghunt at spawn)
`[Craft Scheduler Thread - 54/WARN]: [BlockQuest] Plugin BlockQuest v2.0-pre1.3 generated an exception while executing task 7446
java.lang.IllegalArgumentException: No enum constant org.bukkit.Particle.DISABLED
	at java.lang.Enum.valueOf(Enum.java:238) ~[?:1.8.0_222]
	at org.bukkit.Particle.valueOf(Particle.java:9) ~[patched_1.14.4.jar:git-Paper-187]
	at me.robifoxx.block.Main.lambda$null$0(Main.java:181) ~[?:?]
	at me.robifoxx.block.Main$$Lambda$3362.0000000081F25560.run(Unknown Source) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-187]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.14.4.jar:git-Paper-187]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.14.4.jar:git-Paper-187]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_222]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_222]
	at java.lang.Thread.run(Thread.java:819) [?:1.8.0_222]`

**Comment by quorn23** [comment]
@barpec12 @LogGits tagging you guys too, as you handled the update for 1.13, hope that is okay :)

**Comment by barpec12** [comment]
This error is version-independent. I made a mistake, sorry. This commit fixes it: https://github.com/RobiFox/BlockQuest/pull/10

**Comment by quorn23** [comment]
Thanks, #10 fixes it for 1.14.4
